version: '3.9'

services:
    php:
        build: .
        volumes:
            - ./:/app
        environment:
            MONGODB_URL: 'mongodb://mongodb:27017/test'
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
        command: --storageEngine wiredTiger

volumes:
    mongodb:
